### ISSUE TITLE
interesting....

### ISSUE THREAD

**Issue by soumith** [alexbw/conda-lua-recipes#1]
love to see what this will lead up to.

**Comment by alexbw** [comment]
Try it out. LuaJIT already installs. 

```
conda install -c alexbw luajit
```

Working on other packages now. Are you familiar with the internals of luarocks? It seems like it's some glue around cmake + curl.

**Comment by soumith** [comment]
we dont actually luarocks build for MOST of our packages. We just use cmake.

For example, installing nn via  "luarocks install nn" executes this command:

https://github.com/torch/nn/blob/master/rocks/nn-scm-1.rockspec#L23

the only thing that the cmake is looking for are variables set by luarocks such as $LUA_BINDIR, $LUA_LIBDIR etc. 

https://github.com/keplerproject/luarocks/wiki/Config-file-format#variables

**Comment by alexbw** [comment]
I see. Shouldn't be too hard. I'll start with Torch7, and move on to the libraries I use after that.

Is there any particularly thorny package that you think I should try earlier rather than later, to test the limits of this process?

**Comment by soumith** [comment]
torch7 will be slightly thorny because it uses cwrap for generating some bindings (cwrap is just another lua package). If you really get through torch7, the others should be a breeze and I can split the work with you.

**Comment by alexbw** [comment]
Yes, just saw the dependencies for torch. I'll do `paths` and `cwrap` first.

**Comment by alexbw** [comment]
`paths` builds just fine, but I need to work with some of the conda devs to see whether I should try adding official support for the Lua language to the conda system, or just hack our way to the finish line. They recently added support for R and Perl, so I see no reason why Lua can't get the same treatment.
