### ISSUE TITLE
segmentation fault on centos

### ISSUE THREAD

**Issue by kirk86** [alexbw/conda-lua-recipes#11]
Hi, thank you for this amazing patch of lua and torch to anaconda. It really makes things so much easier, especially for those operating on clusters without sudo permissions.

I've tried to install `conda-lua-recipes` on a centos machine in which I've had pre-installed anaconda (tested and working fine.)

It installed fine without any problems, but when I called the torch repl `th`, I got a segmentation fault error. Usually in my experience this comes from incompatible binaries, for instance maybe compiled with another compiler `clang` instead of `gcc` on another system.

Is `conda-lua-recipes` only for `mac os` systems?

Here is the kernel dump error:

`lua[21087]: segfault at f8 ip 000000377600b716 sp 00007fff1ed5a910 error 4 in ld-2.12.so[3776000000+20000]`
`lua[21103]: segfault at f8 ip 000000377600b716 sp 00007fff8aa25e20 error 4 in ld-2.12.so[3776000000+20000]`
`lua[21116]: segfault at f8 ip 000000377600b716 sp 00007fffdb1b23f0 error 4 in ld-2.12.so[3776000000+20000]`
`lua[22013]: segfault at f8 ip 000000377600b716 sp 00007fffae7218c0 error 4 in ld-2.12.so[3776000000+20000]`

I tried to find the dependencies of `ld-2.12.so` but is statically linked. In my system is under `/lib/ld-2.12.so` and `/lib64/ld-2.12.so`. Do you think that might be an issue?

**Comment by alexbw** [comment]
It definitely is built for Linux, but might require a relatively modern OS (I think I built it on Ubuntu 14).
What CentOS version? For example, it likely won't work on version 5 or 6 without recompiling everything. 
If you have a linux box available for me to rebuild on, I could certainly do it.

**Comment by kirk86** [comment]
Ah I see. The version of centos is 6.6. That's why it might not be working? Correct me if I'm wrong but usually when we install packages using conda or either pip they fetch pre-compiled binaries to save time, but it is possible when installing x or y package to inform the package manager to install from source, i.e. to build the package from source instead of fetching pre-compiled wheels. Can we do the same with `conda-lua-recipes`? Will that work?

**Comment by alexbw** [comment]
That is unfortunately not an option with conda, it always installs binaries.
What version if your GLIBC? Is it 2.12, like your LD version?

**Comment by kirk86** [comment]
Yes GLIBC=2.12 version. If I create a vm with same os and compile there `conda-lua-recipes` then would I be able to incorporate the binaries to `anaconda`?

**Comment by alexbw** [comment]
Yes, you could upload them into your own conda channel, or install them
locally after you've built them using

conda install MYPACKAGES --use-local

**Comment by kirk86** [comment]
That's great. So I guess it all boils down to `sh build_all.sh` correct?

**Comment by alexbw** [comment]
It should yes. Not sure if it will build all the way through out of the
box, so just watch the logs to make sure.

**Comment by kirk86** [comment]
Thanks I'll give it a go and I'll update in case of any news!

**Comment by kirk86** [comment]
Hi, when I try to build `conda-lua-recipes`, I'm getting the following outputs. Any ideas into where the error might rely?

`Traceback (most recent call last):`
 `File "/home/user/anaconda2/bin/conda-build", line 6, in <module>`
    `sys.exit(conda_build.cli.main_build.main())`
 `File "/home/user/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 234, in main`
   `execute(sys.argv[1:])`
 `File "/home/user/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 195, in execute`
    `set_language_env_vars(args, parser, config=config, execute=execute)`
  `File "/home/user/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 43, in set_language_env_vars`
    `execute(args, parser, config)`
`TypeError: execute() takes exactly 1 argument (3 given)`
`Traceback (most recent call last):`
  `File "/home/user/anaconda2/bin/conda-build", line 6, in <module>`
    `sys.exit(conda_build.cli.main_build.main())`
 `File "/home/user/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 234, in main`
    `execute(sys.argv[1:])`
  `File "/home/user/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 195, in execute`
    `set_language_env_vars(args, parser, config=config, execute=execute)`
  `File "/home/user/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 43, in set_language_env_vars`
    `execute(args, parser, config)`
`TypeError: execute() takes exactly 1 argument (3 given)`

Initially prior to updating `conda-build` I got the following errors:

`Warning: failed to download source.  If building, will try again after downloading recipe dependencies.`
`Error was:`
`Command '['/usr/bin/git', 'clone', '--mirror', u'git://github.com/LuaDist/luabitop.git',` `u'/home/user/anaconda2/conda-bld/git_cache/__github.com_LuaDist_luabitop.git']' returned non-zero exit status 128`
`Removing old build environment`
`BUILD START: lua-luabitop-1.0.2-lua5.1_0`
    `(actual version deferred until further download or env creation)`
`Packages missing in current linux-64 channels:`
  `- luarocks`
  `- lua 5.1*`
`Missing dependency luarocks, but found recipe directory, so building luarocks first`
`Packages missing in current linux-64 channels:`
  `- luarocks`
  `- lua 5.1*`
`Missing dependency lua, but found recipe directory, so building lua first`
`Removing old build environment`
`BUILD START: lua-nnx-0.1.1-lua2.0_0`
`Packages missing in current linux-64 channels:`
  `- lua 2.0*`
  `- luarocks`
  `- loa-torch`
  `- lua-nn`
  `- lua-xlua`
`Missing dependency lua, but found recipe directory, so building lua first`
`github.com[0: 192.30.253.113]: errno=Connection timed out`
`fatal: unable to connect a socket (Connection timed out)`
`Using Anaconda Cloud api site https://api.anaconda.org`

`WARNING: conda-build appears to be out of date. You have version 1.21.11 but the
latest version is 2.0.0. Run`

`conda update -n root condo-build`

`to get the latest version.`

`Packages missing in current linux-64 channels:`
 `- luarocks`
 `- lua 5.1*`
`Note: checking out '1228392'.`

`HEAD is now at 1228392... Merge pull request #62 from SeanNaren/master`
`Using Anaconda Cloud api site https://api.anaconda.org`

**Comment by alexbw** [comment]
Any way you could share a VM for me to try this on? For older machines,
debugging these types of things can be kind of finicky.

**Comment by kirk86** [comment]
Ok I'll try to set up one. Can I ask something last. What's the proper way to uninstall `lua-science` from  anaconda. I tried sth like `conda remove lua-science` and it's trying to downgrade a whole lot of packages which I guess depend on `lua-science` including my python version.

Is that the correct way to uninstall it?

**Comment by alexbw** [comment]
On my system, I can do "conda uninstall lua*" and it takes all lua packages
out. I'm not sure if that works everywhere, though.

**Comment by kirk86** [comment]
thanks, that removes only `lua` in my system and not `lua-audio`, `lua-argcheck`, `lua-*` `fftw`, etc. I guess I'll have to go semi-manually.

**Comment by alexbw** [comment]
Bummer. You could also do conda list | grep lua | SOME SMALL AWK COMMAND
HERE | xargs -I {} conda remove {}

**Comment by kirk86** [comment]
yeah, that's exactly what I did ;)

**Comment by alexbw** [comment]
Nice:)

**Comment by kirk86** [comment]
Hey alex, I've created a virtual box image [here](https://mab.to/LnDFAlBIe), with the same os version I was trying to compile `conda-lua-recipes` on, that gave me those compile errors above.

Two accounts on the image:
1. user
2. root

pass: 123456 for both.

Thanks.

**Comment by alexbw** [comment]
Thanks for this, I'll give it a go soon

**Comment by kirk86** [comment]
no worries. Thank you!
