### ISSUE TITLE
Remaining packages

### ISSUE THREAD

**Issue by alexbw** [alexbw/conda-lua-recipes#2]
- [x] nn
- [x] nnx
- [x] cutorch (requires CUDA to be pre-installed. Not sure how to get around this)
- [x] cunn
- [x] optim
- [x] sdl2
- [x] threads
- [x] argcheck
- [x] audio
- [x] fftw3
- [x] signal
- [x] [torch-hdf5](https://github.com/deepmind/torch-hdf5)
- [x] [torch-totem](https://github.com/deepmind/torch-totem)
- [x] [torch-randomkit](https://github.com/deepmind/torch-randomkit)
- [x] [torch-distributions](https://github.com/deepmind/torch-distributions)
- [x] [lua-pprint](https://github.com/deepmind/lua-pprint)
- [x] [torch-cephes](https://github.com/deepmind/torch-cephes)
- [ ] qtlua
- [ ] itorch (should probably build against jupyter, and not IPython)
- [ ] [oxnn](https://github.com/tkocisky/oxnn)
- [ ] fbtorch
- [ ] fbnn
- [ ] fbcunn
  - [ ] fbthrift
  - [ ] folly
  - [ ] thpp
  - [ ] fblualib

**Comment by alexbw** [comment]
@soumith https://github.com/alexbw/conda-lua-recipes/wiki/Anatomy-Of-a-Conda-Recipe

**Comment by alexbw** [comment]
I think iTorch needs to mostly be a `post-link.sh` job, since it relies so heavily on the installed IPython.

**Comment by alexbw** [comment]
Most everything works now. I haven't tackled any of the facebook-specific libraries yet (lots of dependencies to build, all achievable) or iTorch. I've been following the conda mailing list, and they recommend building against Jupyter, which supports installing kernels into $PREFIX directories.

**Comment by alexbw** [comment]
@soumith I've got everything done except for fb-specific libraries. I'd love to help out getting those conda-installable. 

Likely will have to make conda recipes for everything that you ordinarily would apt-get. But if everything is (c)make-able, it wouldn't take more than a few hours (excluding actual build time).

**Comment by soumith** [comment]
@alexbw I've looked at building folly and fbthrift for binstar. It looks like I might have to additionally build a few dependencies in turn as well. And some of the dependencies dont have OSX equivalents. Work in progress at low priority.

**Comment by alexbw** [comment]
Cool. A lot of stuff is pre-built by the binstar community, can check e.g. `binstar search snappy`.
