### ISSUE TITLE
Support for plain Lua

### ISSUE THREAD

**Issue by alexbw** [alexbw/conda-lua-recipes#4]
Right now, everything is hard-coded to work with Luajit.
I'm not sure currently how to support both Lua and Luajit without duplicating every package. 

Perhaps a featured metapackage? That's a thing that I don't fully understand. Conda "features" are for MKL-enabled packages.

**Comment by alexbw** [comment]
This also turns out to be required for qtlua.

**Comment by soumith** [comment]
I'm trying to compile plain lua 5.1, but it seems to have compile errors. Do you know what's up?

``` bash
git clone https://github.com/alexbw/conda-lua-recipes
cd conda-lua-recipes
conda clean --index-cache --packages --source-cache
conda build lua-5.1.5
```

Log here: https://gist.github.com/9bde83973ff30b626c8c

**Comment by alexbw** [comment]
Linux? I have so far only tested on Mac OS X. I had to patch PUC Lua for it to use relative include paths, otherwise it always looks in `/usr/local`, so something might be off with the patch. Won't be a big problem to fix, I just need to get on a Linux box, but that won't happen for a week or so.

**Comment by soumith** [comment]
I've got fixes ready for this. But I dont know how to generate this file: https://github.com/alexbw/conda-lua-recipes/blob/master/lua-5.1.5/update.patch , any ideas?
