### ISSUE TITLE
Capacity reached 

### ISSUE THREAD

**Issue by i55code** [alexbw/conda-lua-recipes#9]
Hi Alex, 

I was trying to install moses, cutorch and cunn, does your code support it now? 

I did: 
[conda-lua-recipes]$ conda build lua-moses --lua="all"
and then: 
[conda-lua-recipes]$ conda install lua-moses  
Fetching package metadata ...Error: HTTPError: 503 Server Error: Service Unavailable: Back-end server is at capacity for url: https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2: https://repo.continuum.io/pkgs/free/linux-64/

Thank you! 

Cheers, 
Zhong

**Comment by i55code** [comment]
[~]$ luarocks install cutorch 

Error: No results matching query were found.
[~]$ luarocks install cunn

Error: No results matching query were found.

**Comment by alexbw** [comment]
Huh, I guess it's become popular. I should probably move everything over to conda-forge.

cutorch and cunn are not currently built for Linux

The luarocks version I bundle with this distribution isn't patched to point to the Torch rocks repos. I'd be happy to walk you through the code if you want to extend this to do so.

**Comment by i55code** [comment]
Is it possible to add cutorch and cunn to it in a simple way? I managed to install all other packages through source, but could not get this two which is super important for GPU.

**Comment by i55code** [comment]
Hi Alex, 

Please point me to the code where I can patch it to Torch rocks repos. 

I hope to extend it. 

Thank you! 

Cheers, 
Zhong

**Comment by alexbw** [comment]
Doesn't seem like there's continuing interest in fixing this right now. Building the required packages right now in Linux.
